# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/wire/types.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message 'wire.Juice' do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :created_at, :message, 3, 'google.protobuf.Timestamp'
    optional :updated_at, :message, 4, 'google.protobuf.Timestamp'
    optional :size, :int32, 5
  end
  add_message 'wire.JuiceList' do
    repeated :juices, :message, 1, 'wire.Juice'
  end
end

module Wire
  Juice = Google::Protobuf::DescriptorPool.generated_pool.lookup('wire.Juice').msgclass
  JuiceList = Google::Protobuf::DescriptorPool.generated_pool.lookup('wire.JuiceList').msgclass
end
